/**
 * Agent file collision detection — zero dependencies.
 *
 * Prevents squad.agent.md (legacy/init) and squad.md (exported coordinator)
 * from coexisting in .github/agents/. Only ONE should be present at a time.
 */

import fs from 'node:fs';
import path from 'node:path';

/**
 * Marker embedded by `squad export agent` in generated squad.md files.
 * Must match the marker in repo-native/write-coordinator-agent.ts exactly.
 */
const EXPORTED_COORDINATOR_MARKER = '<!-- generated by squad export: do not edit by hand -->';

/**
 * Check whether an exported coordinator agent (squad.md) exists in the
 * .github/agents/ directory. If it does, writing squad.agent.md would
 * cause a collision — both files register the "squad" agent identity.
 *
 * @param root - The repository root (or agentFileRoot).
 * @returns The path to the exported file if it exists, or null.
 */
export function detectExportedCoordinator(root: string): string | null {
  const exportedPath = path.join(root, '.github', 'agents', 'squad.md');

  try {
    if (!fs.existsSync(exportedPath)) return null;
    const content = fs.readFileSync(exportedPath, 'utf-8');
    if (content.includes(EXPORTED_COORDINATOR_MARKER)) {
      return exportedPath;
    }
  } catch {
    // Can't read → treat as not present
  }

  return null;
}

/**
 * Returns true if writing squad.agent.md at the given root would collide
 * with an already-exported coordinator (squad.md).
 */
export function wouldCollideWithExport(root: string): boolean {
  return detectExportedCoordinator(root) !== null;
}
