/**
 * Agent file collision prevention tests.
 *
 * Ensures squad.agent.md is NEVER written when an exported coordinator
 * (squad.md with the generated marker) already exists in .github/agents/.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { wouldCollideWithExport, detectExportedCoordinator } from '../../packages/squad-sdk/src/config/agent-collision.js';

describe('agent-collision detection', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'squad-collision-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('returns null when no .github/agents/ exists', () => {
    expect(detectExportedCoordinator(tmpDir)).toBeNull();
    expect(wouldCollideWithExport(tmpDir)).toBe(false);
  });

  it('returns null when .github/agents/ exists but no squad.md', () => {
    fs.mkdirSync(path.join(tmpDir, '.github', 'agents'), { recursive: true });
    expect(detectExportedCoordinator(tmpDir)).toBeNull();
    expect(wouldCollideWithExport(tmpDir)).toBe(false);
  });

  it('returns null when squad.md exists but lacks the generated marker', () => {
    const agentsDir = path.join(tmpDir, '.github', 'agents');
    fs.mkdirSync(agentsDir, { recursive: true });
    fs.writeFileSync(path.join(agentsDir, 'squad.md'), '# My custom agent file\n');
    expect(detectExportedCoordinator(tmpDir)).toBeNull();
    expect(wouldCollideWithExport(tmpDir)).toBe(false);
  });

  it('detects collision when squad.md has the generated marker', () => {
    const agentsDir = path.join(tmpDir, '.github', 'agents');
    fs.mkdirSync(agentsDir, { recursive: true });
    const exported = '---\nname: Squad\n---\n<!-- generated by squad export: do not edit by hand -->\n# Coordinator\n';
    fs.writeFileSync(path.join(agentsDir, 'squad.md'), exported);

    const result = detectExportedCoordinator(tmpDir);
    expect(result).toBe(path.join(agentsDir, 'squad.md'));
    expect(wouldCollideWithExport(tmpDir)).toBe(true);
  });

  it('detects collision even with marker deep in file', () => {
    const agentsDir = path.join(tmpDir, '.github', 'agents');
    fs.mkdirSync(agentsDir, { recursive: true });
    const exported = '---\nname: Squad\n---\n\n# Big file\n\nLots of content...\n\n<!-- generated by squad export: do not edit by hand -->\n\nMore content.\n';
    fs.writeFileSync(path.join(agentsDir, 'squad.md'), exported);

    expect(wouldCollideWithExport(tmpDir)).toBe(true);
  });
});
