/**
 * File writer for the coordinator agent export.
 * Handles write, check, dry-run, and legacy collision detection.
 */

import fs from 'node:fs';
import path from 'node:path';

export interface WriteOptions {
  root: string;
  outputPath: string;
  output: string;
  check: boolean;
  dryRun: boolean;
  force: boolean;
  cleanLegacyAgent: boolean;
}

export interface WriteResult {
  written: boolean;
  driftDetected: boolean;
  /** The target file exists but was not generated by squad export */
  userOwned: boolean;
  legacyCollision: boolean;
  legacyCleaned: boolean;
  outputPath: string;
}

const GENERATED_MARKER = '<!-- generated by squad export: do not edit by hand -->';
const PROTECTED_AGENT_FILE = 'squad.agent.md';

function isProtectedAgentFile(filePath: string): boolean {
  return path.basename(filePath) === PROTECTED_AGENT_FILE;
}

/**
 * Check if an existing file was generated by squad export.
 */
function isSquadGenerated(filePath: string): boolean {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    return content.includes(GENERATED_MARKER);
  } catch {
    return false;
  }
}

/**
 * Reserved for future legacy detection.
 */
function detectLegacyAgentFile(_root: string): string | null {
  return null;
}

/**
 * Write the coordinator agent file with safety checks.
 */
export function writeCoordinatorAgent(options: WriteOptions): WriteResult {
  const { root, outputPath, output, check, dryRun, force } = options;
  const fullOutputPath = path.isAbsolute(outputPath)
    ? outputPath
    : path.join(root, outputPath);

  if (isProtectedAgentFile(fullOutputPath)) {
    throw new Error(
      "Cannot write to squad.agent.md — this file is the project's coordinator governance file and must not be modified by export. Use a different output path (default: squad.md)."
    );
  }

  const result: WriteResult = {
    written: false,
    driftDetected: false,
    userOwned: false,
    legacyCollision: false,
    legacyCleaned: false,
    outputPath: fullOutputPath,
  };

  // Reserved for future legacy file handling.
  const legacyPath = detectLegacyAgentFile(root);
  if (legacyPath) {
    result.legacyCollision = true;
  }

  // Check mode: compare without writing
  if (check) {
    try {
      const existing = fs.readFileSync(fullOutputPath, 'utf-8');
      if (!existing.includes(GENERATED_MARKER)) {
        // File exists but is user-owned — distinct from drift
        result.userOwned = true;
        return result;
      }
      result.driftDetected = existing !== output;
    } catch {
      // File doesn't exist = drift
      result.driftDetected = true;
    }
    return result;
  }

  // Dry-run mode: print but don't write
  if (dryRun) {
    process.stdout.write(output);
    return result;
  }

  // Safety: don't overwrite user-owned files unless --force
  if (fs.existsSync(fullOutputPath) && !isSquadGenerated(fullOutputPath) && !force) {
    throw new Error(
      `${fullOutputPath} exists and was not generated by squad export. ` +
      `Use --force to overwrite or remove it manually.`
    );
  }

  // Ensure directory exists
  const dir = path.dirname(fullOutputPath);
  fs.mkdirSync(dir, { recursive: true });

  // Write the file
  fs.writeFileSync(fullOutputPath, output, 'utf-8');
  result.written = true;

  return result;
}
